# MIT License
#
# Copyright (c) 2009-2024 Zerocracy
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
docker:
  image: yegor256/rultor-java
ec2:
  type: t2.medium
readers:
  - "urn:github:526301"
assets:
  config.yml: yegor256/home#assets/zerocracy/baza.yml
install: |-
  set -x
  pdd -f /dev/null
  sudo apt-get update
  sudo apt-get install -y libpq-dev postgresql-client postgresql
  sudo ln -s "$(realpath /usr/lib/postgresql/*/bin/initdb)" /bin/initdb
  sudo ln -s "$(realpath /usr/lib/postgresql/*/bin/postgres)" /bin/postgres
  bundle install --no-color
  bundle install --no-color --gemfile=assets/lambda/Gemfile
  bundle install --no-color --gemfile=swarms/alterations/Gemfile
merge:
  script: |-
    set -x
    bundle exec rake
    sed -i "s/0\.0\.0/v${BRANCH}/g" ./version.rb
    git add ./version.rb
    git commit -m 'build number set'
    cp ../config.yml target/pgsql-config.yml
    bundle exec rake liquibase
    rm target/pgsql-config.yml
